var data = [
  {
    key: "ARGF_at",
    value: -0.049
  }, {
    key: "DNAJ_at",
    value: -0.011
  }, {
    key: "LYSC_at",
    value: -0.049
  }, {
    key: "RPLL_at",
    value: -0.007
  }, {
    key: "SPOIISA_at",
    value: 0.134
  }, {
    key: "XHLA_at",
    value: 0.066
  }, {
    key: "XHLB_at",
    value: 0.018
  }, {
    key: "XKDS_at",
    value: 0.064
  }, {
    key: "XLYA_at",
    value: 0.024
  }, {
    key: "XTRA_at",
    value: 0.195
  }, {
    key: "YBFI_at",
    value: 0.000
  }, {
    key: "YCGO_at",
    value: 0.000
  }, {
    key: "YCKE_at",
    value: 0.132
  }, {
    key: "YDDK_at",
    value: -0.166
  }, {
    key: "YEBC_at",
    value: -0.281
  }, {
    key: "YEZB_at",
    value: 0.008
  }, {
    key: "YHCL_at",
    value: -0.044
  }, {
    key: "YOAB_at",
    value: -0.447
  }, {
    key: "YRVJ_at",
    value: -0.034
  }, {
    key: "YURQ_at",
    value: 0.105
  }, {
    key: "YXLD_at",
    value: -0.254
  }, {
    key: "YYDA_at",
    value: -0.005
  },
];
